<a href="https://colab.research.google.com/github/4M5/My_Learnings/blob/main/Base_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. ====>PANDAS

In [1]:
import pandas as p
frame=p.DataFrame()
print(frame)

Empty DataFrame
Columns: []
Index: []


In [2]:
a=[[1,2,3,4,5],[6,7,8,9,10]]
frame2=p.DataFrame(a)
print(frame2)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [3]:
b=[["KTU","Place","Code"],["TKM","Kollam",1234],["CET","TVM",56789]]
fram=p.DataFrame(b)
print(fram)

     0       1      2
0  KTU   Place   Code
1  TKM  Kollam   1234
2  CET     TVM  56789


In [4]:
print(fram.ndim)

2


In [5]:
#DICTIONARY-------
dict={"Name":["Abey","Anil"],"Age":[23,50]}
print(dict)
dframe=p.DataFrame(dict)
print(dframe)
print(dframe.dtypes)

{'Name': ['Abey', 'Anil'], 'Age': [23, 50]}
   Name  Age
0  Abey   23
1  Anil   50
Name    object
Age      int64
dtype: object


In [6]:
dframe.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Columns: 2 entries, Name to Age
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes


In [7]:
dframe.values

array([['Abey', 23],
       ['Anil', 50]], dtype=object)

In [8]:
dframe.size

4

2. ====>NUMPY

In [9]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
one=np.ones((4,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
zero=np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
y=np.array(['TKM','College',28,8,2022])
print(y)

['TKM' 'College' '28' '8' '2022']


In [13]:
arr1=np.arange(start=10,stop=101,step=5)
print(arr1)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [14]:
np.random.rand(50)

array([0.32040623, 0.0166916 , 0.80824452, 0.18794958, 0.36485313,
       0.07723253, 0.38982041, 0.06806807, 0.47886924, 0.48062795,
       0.69563705, 0.35155509, 0.90046827, 0.38949344, 0.2234555 ,
       0.21839035, 0.88796556, 0.4101079 , 0.17163655, 0.72185815,
       0.35670258, 0.1515978 , 0.24847807, 0.17612406, 0.02482371,
       0.13106345, 0.28133512, 0.50221738, 0.13946561, 0.93123926,
       0.97228396, 0.10075528, 0.41806142, 0.63996142, 0.4540096 ,
       0.14086265, 0.72195418, 0.95437727, 0.28266219, 0.6767005 ,
       0.86785342, 0.8760537 , 0.64394951, 0.14735931, 0.95058851,
       0.26400112, 0.03237336, 0.81261647, 0.83427715, 0.82593933])

In [15]:
data=np.array([[1,2,3],[4,5,6],[7,8,9],[10,15,7]])
print(data)
print(data.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 15  7]]
(4, 3)


In [16]:
datas=data.reshape(3,4)
print(datas)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 15  7]]


In [17]:
arr1=np.array([[2,4,6],[1,2,3],[5,7,8]])
arr2=np.array([[1,1,1],[2,2,2],[3,3,3]])
add=np.add(arr1,arr2)
print(add)

[[ 3  5  7]
 [ 3  4  5]
 [ 8 10 11]]


In [18]:
#mul=element multiplication

mul=np.multiply(arr1,arr2)

#dot=matrix multiplication

dot=np.dot(arr1,arr2)
print(mul)
print(dot)

[[ 2  4  6]
 [ 2  4  6]
 [15 21 24]]
[[28 28 28]
 [14 14 14]
 [43 43 43]]
