In [3]:
#tokenisation
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt_tab')

example_sent = """This is a sample sentence,
                  showing off the stop words filtration."""
word_tokens = word_tokenize(example_sent)
print(word_tokens)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...


['This', 'is', 'a', 'sample', 'sentence', ',', 'showing', 'off', 'the', 'stop', 'words', 'filtration', '.']


[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [5]:
#stop word removal (a,an,the) which is not signifcant for training
nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...


['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

[nltk_data]   Unzipping corpora/stopwords.zip.


In [6]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

# Download necessary resources
nltk.download('stopwords')
nltk.download('punkt')

example_sent = """This is a sample sentence,
                  showing off the stop words filtration."""

# Load stopwords
stop_words = set(stopwords.words('english'))

# Tokenize sentence
word_tokens = word_tokenize(example_sent)

# Remove stopwords and punctuation (corrected approach)
filtered_sentence = [w for w in word_tokens if w.lower() not in stop_words and w not in string.punctuation]

print("Original Tokens:", word_tokens)
print("Filtered Tokens:", filtered_sentence)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Original Tokens: ['This', 'is', 'a', 'sample', 'sentence', ',', 'showing', 'off', 'the', 'stop', 'words', 'filtration', '.']
Filtered Tokens: ['sample', 'sentence', 'showing', 'stop', 'words', 'filtration']


In [7]:
#Stemming (removes suffixes like ing)
import nltk
nltk.download('stopwords')
nltk.download('punkt_tab')
from nltk.stem.snowball import SnowballStemmer
from nltk.tokenize import word_tokenize

stemmer = SnowballStemmer("english", True)
text = "There is nothing either good or bad but thinking makes it so."
words = word_tokenize(text)
stemmed_words = [stemmer.stem(word) for word in words]

print("Original:", text)
print("Tokenized:", words)
print("Stemmed:", stemmed_words)


Original: There is nothing either good or bad but thinking makes it so.
Tokenized: ['There', 'is', 'nothing', 'either', 'good', 'or', 'bad', 'but', 'thinking', 'makes', 'it', 'so', '.']
Stemmed: ['there', 'is', 'noth', 'either', 'good', 'or', 'bad', 'but', 'think', 'make', 'it', 'so', '.']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [10]:
#Lemmatization (exactly like stemming it distill words to foundation form)
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print("rocks :", lemmatizer.lemmatize("rocks"))
print("corpora :", lemmatizer.lemmatize("corpora"))

# a denotes adjective in "pos"
print("better :", lemmatizer.lemmatize("better", pos="a"))
# import these modules
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print("rocks :", lemmatizer.lemmatize("rocks"))
print("corpora :", lemmatizer.lemmatize("corpora"))

# a denotes adjective in "pos"
print("better :", lemmatizer.lemmatize("better", pos="a"))

rocks : rock
corpora : corpus
better : good
rocks : rock
corpora : corpus
better : good


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


.

**CHATBOT**

In [19]:
from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir('/content/drive/MyDrive/Lab/Chatbot')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [18]:
!pip install livelossplot --quiet

In [16]:
#2 Importing Relevant Libraries
import json  # For loading and parsing JSON data

import string  # For handling string operations, such as punctuation removal
import random  # For generating random numbers, useful in training data shuffling

import nltk  # Natural Language Toolkit, used for text preprocessing
import numpy as np  # NumPy, for numerical computations and array manipulations

from nltk.stem import WordNetLemmatizer  # For lemmatization (reducing words to their base form)
import tensorflow as tf  # TensorFlow, a deep learning framework
from tensorflow.keras import Sequential  # Sequential model for building neural networks
from tensorflow.keras.layers import Dense, Dropout  # Dense for fully connected layers, Dropout for regularization

import livelossplot  # For real-time visualization of loss and accuracy during training
from livelossplot import PlotLossesKeras  # Keras callback to plot training progress
nltk.download("punkt")
nltk.download('punkt_tab') ## Toke
nltk.download("wordnet")   # dictionary for the English language; for lemmatization

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [20]:
#3 Loading the Dataset: intents.json

data_file = open('intents.json').read()
data = json.loads(data_file)

data

{'intents': [{'tag': 'hello',
   'patterns': ['Hello', 'Hi there', 'Good morning', "What's up"],
   'responses': ['Hey!', 'Hello', 'Hi!', 'Good morning!'],
   'context': ''},
  {'tag': 'noanswer',
   'patterns': [],
   'responses': ["Sorry, can't understand you",
    'Please give me more info',
    'Not sure I understand'],
   'context': ['']},
  {'tag': 'job',
   'patterns': ['What is your job', 'What is your work'],
   'responses': ['My job is to make you feel like everything is okay.',
    'I work to serve you as well as possible'],
   'context': ''},
  {'tag': 'age',
   'patterns': ['What is your age', 'How old are you', 'When were you born'],
   'responses': ['I was born in 2021'],
   'context': ''},
  {'tag': 'feeling',
   'patterns': ['How are you today', 'How are you'],
   'responses': ['I am feeling good, you?',
    'Very good and you?',
    "Actually, I'm okay and you?"],
   'context': ''},
  {'tag': 'good',
   'patterns': ['I am good too',
    'I feel fine',
    'Good !',
  

In [21]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
corpus = [
    "I love cats and dogs",
    "I love dogs",
    "Cats and dogs are amazing"
]

In [24]:
vectorizer = CountVectorizer()  # Initialize BoW model
X = vectorizer.fit_transform(corpus)  # Fit and transform text into BoW vectors

# Convert the sparse matrix to an array for readability
bow_array = X.toarray()
# Print the vocabulary (word index mapping)
print("Vocabulary:", (vectorizer.vocabulary_))

# Print the BoW representation of each sentence
print("Bag of Words Matrix:\n", bow_array)


Vocabulary: {'love': 5, 'cats': 3, 'and': 1, 'dogs': 4, 'are': 2, 'amazing': 0}
Bag of Words Matrix:
 [[0 1 0 1 1 1]
 [0 0 0 0 1 1]
 [1 1 1 1 1 0]]


In [25]:
#4 Extracting data_X(features) and data_Y(Target)

words = [] #For Bow model/ vocabulary for patterns
classes = [] #For Bow  model/ vocabulary for tags
data_X = [] #For storing each pattern
data_y = [] #For storing tag corresponding to each pattern in data_X
# Iterating over all the intents

for intent in data["intents"]:
    print(intent)
    for pattern in intent["patterns"]:
        print(pattern)
        tokens = nltk.word_tokenize(pattern) # tokenize each pattern
        words.extend(tokens
) #and append tokens to words
        data_X.append(pattern) #appending pattern to data_X
        data_y.append(intent["tag"]) ,# appending the associated tag to each pattern

    # adding the tag to the classes if it's not there already
    if intent["tag"] not in classes:
        classes.append(intent["tag"])

# initializing lemmatizer to get stem of words
lemmatizer = WordNetLemmatizer()

# lemmatize all the words in the vocab and convert them to lowercase
# if the words don't appear in punctuation
words = [lemmatizer.lemmatize(word.lower()) for word in words if word not in string.punctuation]
# sorting the vocab and classes in alphabetical order and taking the # set to ensure no duplicates occur
words = sorted(set(words)) #vocabulary
classes = sorted(set(classes))

{'tag': 'hello', 'patterns': ['Hello', 'Hi there', 'Good morning', "What's up"], 'responses': ['Hey!', 'Hello', 'Hi!', 'Good morning!'], 'context': ''}
Hello
Hi there
Good morning
What's up
{'tag': 'noanswer', 'patterns': [], 'responses': ["Sorry, can't understand you", 'Please give me more info', 'Not sure I understand'], 'context': ['']}
{'tag': 'job', 'patterns': ['What is your job', 'What is your work'], 'responses': ['My job is to make you feel like everything is okay.', 'I work to serve you as well as possible'], 'context': ''}
What is your job
What is your work
{'tag': 'age', 'patterns': ['What is your age', 'How old are you', 'When were you born'], 'responses': ['I was born in 2021'], 'context': ''}
What is your age
How old are you
When were you born
{'tag': 'feeling', 'patterns': ['How are you today', 'How are you'], 'responses': ['I am feeling good, you?', 'Very good and you?', "Actually, I'm okay and you?"], 'context': ''}
How are you today
How are you
{'tag': 'good', 'patte

In [27]:
# 5 Text to Numbers
training = []
out_empty = [0] * len(classes) #out_empty: A list of zeros of length equal to the number of classes.
                                #This will be used to create a one-hot encoded vector for classification.
# creating the bag of words model
for idx, doc in enumerate(data_X):
    print(doc)
    bow = []
    text = lemmatizer.lemmatize(doc.lower())
    for word in words:

        bow.append(1) if word in text else bow.append(0) #This creates a binary vector representation of the text.
    # mark the index of class that the current pattern is associated
    # to
    output_row = list(out_empty)
    output_row[classes.index(data_y[idx])] = 1 #one-hot encoded label vector
    # add the one hot encoded BoW and associated classes to training
    training.append([bow, output_row])
# shuffle the data and convert it to an array
random.shuffle(training)
training = np.array(training, dtype=object)
# split the features and target labels
train_X = np.array(list(training[:, 0]))
train_Y = np.array(list(training[:, 1]))

Hello
Hi there
Good morning
What's up
What is your job
What is your work
What is your age
How old are you
When were you born
How are you today
How are you
I am good too
I feel fine
Good !
Fine
I am good
I am great
great
I am feeling bad
No I am sad
No
What can you do
What can I ask you
Can you help me
Are you a girl
You are a women
Are you a men
Are you a boy
Thank you
Thank you very much
thanks
Goodbye
Good afternoon
Bye
Where do you live
What are you doing
Can you wait 2 minutes
Please wait
Wait 2 secs please
Are you still there?
Are you here?
