1. ====>PANDAS

In [ ]:
import pandas as p
frame=p.DataFrame()
print(frame)

Empty DataFrame
Columns: []
Index: []


In [ ]:
a=[[1,2,3,4,5],[6,7,8,9,10]]
frame2=p.DataFrame(a)
print(frame2)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [ ]:
b=[["KTU","Place","Code"],["TKM","Kollam",1234],["CET","TVM",56789]]
fram=p.DataFrame(b)
print(fram)

     0       1      2
0  KTU   Place   Code
1  TKM  Kollam   1234
2  CET     TVM  56789


In [ ]:
print(fram.ndim)

2


In [ ]:
#DICTIONARY-------
dict={"Name":["Abey","Anil"],"Age":[23,50]}
print(dict)
dframe=p.DataFrame(dict)
print(dframe)
print(dframe.dtypes)

{'Name': ['Abey', 'Anil'], 'Age': [23, 50]}
   Name  Age
0  Abey   23
1  Anil   50
Name    object
Age      int64
dtype: object
<bound method DataFrame.info of    Name  Age
0  Abey   23
1  Anil   50>


In [ ]:
dframe.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Columns: 2 entries, Name to Age
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [ ]:
dframe.values

array([['Abey', 23],
       ['Anil', 50]], dtype=object)

In [ ]:
dframe.size

4

2. ====>NUMPY

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(x)
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
one=np.ones((4,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
zero=np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [1]:
y=np.array(['TKM','College',28,8,2022])
print(y)

NameError: name 'np' is not defined

In [2]:
arr1=np.arange(start=10,stop=101,step=5)
print(arr1)

NameError: name 'np' is not defined

In [ ]:
np.random.rand(50)

array([0.74208257, 0.34881054, 0.05871647, 0.41518554, 0.06307935,
       0.23439385, 0.65741099, 0.09485801, 0.35196685, 0.44791641,
       0.84235729, 0.21199531, 0.03862812, 0.95719161, 0.64944574,
       0.99160723, 0.25992945, 0.2593385 , 0.88613595, 0.16976363,
       0.30990783, 0.80887617, 0.37499562, 0.70951817, 0.92574335,
       0.47605868, 0.98218486, 0.512369  , 0.87776456, 0.17164513,
       0.11943485, 0.02527128, 0.01188667, 0.00886611, 0.9630925 ,
       0.34191508, 0.32177169, 0.38031901, 0.33484179, 0.65780418,
       0.57771882, 0.67182412, 0.60530708, 0.68012395, 0.88216461,
       0.3830672 , 0.16217491, 0.86257219, 0.70282859, 0.43209899])

In [ ]:
data=np.array([[1,2,3],[4,5,6],[7,8,9],[10,15,7]])
print(data)
print(data.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 15  7]]
(4, 3)


In [ ]:
datas=data.reshape(3,4)
print(datas)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 15  7]]


In [ ]:
arr1=np.array([[2,4,6],[1,2,3],[5,7,8]])
arr2=np.array([[1,1,1],[2,2,2],[3,3,3]])
add=np.add(arr1,arr2)
print(add)

[[ 3  5  7]
 [ 3  4  5]
 [ 8 10 11]]


In [ ]:
#mul=element multiplication

mul=np.multiply(arr1,arr2)

#dot=matrix multiplication

dot=np.dot(arr1,arr2)
print(mul)
print(dot)

[[ 2  4  6]
 [ 2  4  6]
 [15 21 24]]
[[28 28 28]
 [14 14 14]
 [43 43 43]]
